---
title: "Modelling First Iteration of Eriogonum coloradense"
author: "steppe"
output: html_document
---

```{r}
library(sf)
library(tidyverse)
library(terra)
source('functions.R')
set.seed(23)
```

Import the ground verified data from the first set of mapping
```{r}
ground_truth <- read.csv('../data/GroundTruthing/Pts.csv') |>
  mutate(
    across(c('Dominant_Phen'), ~ na_if(., '')), 
    across(Presence_M:Presence_J, ~ replace_na(., 0)))

# this whole 'r' random points thing needs to be done separately for both the
# cochetopa and the  other set of points !!
rand_pts_iter1 <- st_read('../data/GroundTruthPts/Iteration1-cp.shp', quiet = T) |>
  select(UID) %>% 
  inner_join(., 
             filter(ground_truth,  Location_abbrevation != 'CD'), 
    by = c('UID' = 'GlobalRandomID')) |>
  mutate(Site = paste0('r-', UID)) |>
  select(-Latitude, -Longitude, -UID) 

rand_pts_iter2 <- st_read('../data/GroundTruthPts/Iteration1-Coechotopa.shp', quiet = T) |>
  select(ID) %>% 
  inner_join(., 
             filter(ground_truth, 
                    str_detect(Site, '[a-z]', negate = TRUE), Location_abbrevation == 'CD') |>
               mutate(Site = as.numeric(Site)), 
    by = c('ID' = 'GlobalRandomID')) |>
  mutate(Site = paste0('r-', ID)) |>
  select(-Latitude, -Longitude) 

rand_pts_iter1 <- bind_rows(rand_pts_iter1, rand_pts_iter2)

ground_truth <- filter(ground_truth, is.na(GlobalRandomID)) # remove these random pts

# THESE NEEDS REDONE - THE COCHETOPA DOME POINTS ARE INTEREFERED WITH THE RIDGE 14043 POINTS!!!!
# objects: 375, 400, 405, 412, 414, 417, 320 433, 434, 435, 451, 454

# we can't perform the same join - if we join the cochetopa data with the full data set, 
# than sites from 13043 ridge will be joined instead. This is because CD points were
# written out later, and seperately, but restart their presence count at 1. 
revisits <- st_read('../data/GroundTruthPts/Revisits-cp.shp', quiet = T) |> 
  select(UID) |> 
  mutate(UID = str_replace(UID, 'P', 'p')) %>%  
  inner_join(., filter(ground_truth, 
                       str_detect(Site, 'p') & Location_abbrevation != 'CD'),
             by = c('UID' = 'Site'))  

# we can safely join the CD sites here. 
revisits_cd <- st_read('../data/GroundTruthPts/Cocheotopa_revisits.shp', quiet = T) |> 
  select(ID) |> 
  mutate(UID = paste0('p-', ID)) %>%  
  inner_join(., filter(ground_truth, 
                       str_detect(Site, 'p') & Location_abbrevation == 'CD'),
             by = c('UID' = 'Site'))  |>
  sf::st_transform(st_crs(revisits))

revisits <- bind_rows(revisits, revisits_cd)

ground_truth <- filter(ground_truth, str_detect(Site, 'p', negate= T)) |>
  select(-GlobalRandomID) |>
  st_as_sf(coords = c(x = 'Longitude', y = 'Latitude'), crs = 4269) |>
  st_transform(st_crs(revisits))

rm(revisits_cd, rand_pts_iter2)
```

We'll turn revisits into two data frames, this will be used to compare the accuracy of the coordinates to the occurrences. 
```{r}
revisits <- filter(revisits, !is.na(Latitude)) |>
  st_drop_geometry() |>
  st_as_sf(coords = c(x = 'Longitude', y = 'Latitude'), crs = 4269) |>
  st_transform(st_crs(revisits)) %>% 
  bind_rows(., filter(revisits, is.na(Latitude))) |>
  mutate(Site = UID) |>
  select(-Latitude, -Longitude, -UID)
```

All data are cleaned now
```{r}
ground_truth <- bind_rows(ground_truth, rand_pts_iter1, revisits) |>
  select(-GlobalRandomID) %>% 
  mutate(Presence = ifelse(Presence_M > 0 | Presence_J > 0, 1, 0), .after = Presence_J)

st_write(ground_truth, '../data/GroundTruthing/QC.shp', append = F)
rm(rand_pts_iter1, revisits)
```

```{r}
gt_pres <- filter(ground_truth, Presence == 1) |>
    dplyr::select(NAME = OBJECT) |>
    sf::st_write(dsn = '../data/GroundTruthing/Presences.kml', driver = 'kml',
                 quiet = T, append = F)

gt_abs <- filter(ground_truth, Presence == 0) |>
    dplyr::select(NAME = OBJECT) |>
    sf::st_write(dsn = '../data/GroundTruthing/Absences.kml', driver = 'kml',
                 quiet = T, append = F)
```

We will add some random points based on my scouting efforts. 
These should hopefully help reduce the effects of spatial auto-correlation. 

```{r}
comp_abs <- read.csv('../data/GroundTruthing/ComputerAbs.csv') |>
  mutate(
    Presence_M = 0, Presence_J = 0, Presence = 0, 
    OBJECT = 1:n() + max(ground_truth$OBJECT)) |>
  st_as_sf(coords = c(x = 'Longitude', y = 'Latitude'), crs = 4326) |>
  st_transform(st_crs(ground_truth))

ab <- bind_rows(ground_truth, comp_abs) |>
  arrange(OBJECT) |>
  st_write('../data/GroundTruthing/Iteration1Pts.shp', append = F)

library(spdep)
nn5 = knn2nb(knearneigh(ab, 8))
w = nb2listw(nn5, style="B")
joincount.test( as.factor(ab$Presence), w)

```

